# Pre-Processing

## 1. Import libraries, get data and create the dataframe

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [3]:
data_path = Path.cwd() / ".." / "data" / "processed" / "healthcare_dataset_semi-processed.csv"
data = pd.read_csv(data_path)

In [4]:
data.head()

,Age,Gender,Blood Type,Medical Condition,Insurance Provider,Admission Type,Medication,Test Results,LOS Category
0,19,Female,AB+,Infections,Blue Cross,Emergency,Azithromycin,Normal,Medium Stay
1,15,Female,B-,Flu,UnitedHealthcare,Emergency,Tamiflu,Abnormal,Short Stay
2,50,Female,A+,Cancer,Blue Cross,Elective,Cisplatin,Inconclusive,Long Stay
3,24,Female,O+,Asthma,Aetna,Elective,Prednisone,Normal,Short Stay
4,80,Female,A+,Heart Disease,Cigna,Routine,Beta-blockers,Inconclusive,Long Stay

In [5]:
data.nunique()

Age                   86
Gender                 2
Blood Type             8
Medical Condition      8
Insurance Provider     5
Admission Type         4
Medication            23
Test Results           3
LOS Category           3
dtype: int64

## 2. Pre-process data

### 2.1 Transform gender in intenger

In [6]:
print(data['Gender'].value_counts())

Gender
Female    27955
Male      27545
Name: count, dtype: int64

In [7]:
data['Gender'] = data['Gender'].map({'Male': 0, 'Female': 1})

### 2.2 One-Hot Encoding + dropping first column to evict dummy variable trap

In [8]:
data = pd.get_dummies(data, columns=['Blood Type', 'Medical Condition', 'Admission Type', 'Medication', 'Test Results'], drop_first=True, dtype=int)

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 45 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Age                              55500 non-null  int64
 1   Gender                           55500 non-null  int64
 2   Insurance Provider               55500 non-null  str
 3   LOS Category                     55500 non-null  str
 4   Blood Type_A-                    55500 non-null  int64
 5   Blood Type_AB+                   55500 non-null  int64
 6   Blood Type_AB-                   55500 non-null  int64
 7   Blood Type_B+                    55500 non-null  int64
 8   Blood Type_B-                    55500 non-null  int64
 9   Blood Type_O+                    55500 non-null  int64
 10  Blood Type_O-                    55500 non-null  int64
 11  Medical Condition_Asthma         55500 non-null  int64
 12  Medical Condition_Cancer         55500 non-null  int64
 13  Medical Condition_Diabetes       55500 non-null  int64
 14  Medical Condition_Flu            55500 non-null  int64
 15  Medical Condition_Heart Disease  55500 non-null  int64
 16  Medical Condition_Infections     55500 non-null  int64
 17  Medical Condition_Obesity        55500 non-null  int64
 18  Admission Type_Emergency         55500 non-null  int64
 19  Admission Type_Routine           55500 non-null  int64
 20  Admission Type_Urgent            55500 non-null  int64
 21  Medication_Amoxicillin           55500 non-null  int64
 22  Medication_Aspirin               55500 non-null  int64
 23  Medication_Azithromycin          55500 non-null  int64
 24  Medication_Beta-blockers         55500 non-null  int64
 25  Medication_Ciprofloxacin         55500 non-null  int64
 26  Medication_Cisplatin             55500 non-null  int64
 27  Medication_Donepezil             55500 non-null  int64
 28  Medication_Doxorubicin           55500 non-null  int64
 29  Medication_Glipizide             55500 non-null  int64
 30  Medication_Insulin               55500 non-null  int64
 31  Medication_Memantine             55500 non-null  int64
 32  Medication_Metformin             55500 non-null  int64
 33  Medication_Methotrexate          55500 non-null  int64
 34  Medication_Montelukast           55500 non-null  int64
 35  Medication_Orlistat              55500 non-null  int64
 36  Medication_Oseltamivir           55500 non-null  int64
 37  Medication_Phentermine           55500 non-null  int64
 38  Medication_Prednisone            55500 non-null  int64
 39  Medication_Rivastigmine          55500 non-null  int64
 40  Medication_Statins               55500 non-null  int64
 41  Medication_Tamiflu               55500 non-null  int64
 42  Medication_Zanamivir             55500 non-null  int64
 43  Test Results_Inconclusive        55500 non-null  int64
 44  Test Results_Normal              55500 non-null  int64
dtypes: int64(43), str(2)
memory usage: 20.0 MB

In [10]:
data.head()

,Age,Gender,Insurance Provider,LOS Category,Blood Type_A-,Blood Type_AB+,Blood Type_AB-,Blood Type_B+,Blood Type_B-,Blood Type_O+,...,Medication_Orlistat,Medication_Oseltamivir,Medication_Phentermine,Medication_Prednisone,Medication_Rivastigmine,Medication_Statins,Medication_Tamiflu,Medication_Zanamivir,Test Results_Inconclusive,Test Results_Normal
0,19,1,Blue Cross,Medium Stay,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,15,1,UnitedHealthcare,Short Stay,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
2,50,1,Blue Cross,Long Stay,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,24,1,Aetna,Short Stay,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,1
4,80,1,Cigna,Long Stay,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

### 2.3 Create new dataframe without insurance provider 
I'll fit both data, with and without insurance provider to compare results

In [11]:
data_without_insurance = data.drop(columns=['Insurance Provider'])

In [12]:
data = pd.get_dummies(data, columns=['Insurance Provider'], drop_first=True, dtype=int)

In [13]:
data.head()

,Age,Gender,LOS Category,Blood Type_A-,Blood Type_AB+,Blood Type_AB-,Blood Type_B+,Blood Type_B-,Blood Type_O+,Blood Type_O-,...,Medication_Rivastigmine,Medication_Statins,Medication_Tamiflu,Medication_Zanamivir,Test Results_Inconclusive,Test Results_Normal,Insurance Provider_Blue Cross,Insurance Provider_Cigna,Insurance Provider_Medicare,Insurance Provider_UnitedHealthcare
0,19,1,Medium Stay,0,1,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
1,15,1,Short Stay,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,1
2,50,1,Long Stay,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
3,24,1,Short Stay,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
4,80,1,Long Stay,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0

## 3. Export processed data

In [ ]:
data.to_csv(Path.cwd() / ".." / "data" / "processed" / "healthcare_dataset_processed.csv", index=False)
data_without_insurance.to_csv(Path.cwd() / ".." / "data" / "processed" / "processed_dataset_without_insurance.csv", index=False)
pd.to_csv(data_without_insurance, Path.cwd() / ".." / "data" / "processed" / "processed_dataset_without_insurance.csv"), index=False)

## 4. Split data by train and test

Variables

In [18]:
y = data['LOS Category']
X1 = data.drop(columns=['LOS Category'])
X2 = data_without_insurance.drop(columns=['LOS Category'])

Splitting

In [19]:
train_X1, test_X1, train_y, test_y = train_test_split(X1, y, test_size=0.2, random_state=42, stratify=y)

Fitting

In [21]:
decision_tree_model = DecisionTreeClassifier(random_state=42)
decision_tree_model.fit(train_X1, train_y)

DecisionTreeClassifier(random_state=42)